### ISSUE TITLE
Display Information/logo when nothing is playing

### ISSUE THREAD

**Issue by Maschine2501** [diehardsk/Volumio-OledUI#1]
Hello!
first of all thank you for your code, great work!
I would like to "modify" the code.
Can you support me?
If Volumio is started and nothing is played yet, nothing is currently displayed on the Oled.
I would prefer to either:
-show the time and system information like IP etc.
-or display a logo
Unfortunately I was not able to find the right point for this in the oledui.py.
Where does it define what is displayed if nothing happens?
I would be very happy about your support!
Greetings!

PS: Your code displays a "Play" and a "stop" icon, where are they stored? I was not able to find a reference.

**Comment by diehardsk** [comment]
Hello. Thanks for your comments and sorry for late reply.
Icons are stored in fa** font file (Font Awesome Icons).
No display state is kind of hot stand-by for me and I don't want to burn oled pixels in this state. But let's say you want to show some text and current time in stop mode. I think the most easy solution is to add your code to main loop at the very end of _oledui.py_. Check for _oled.playState == 'stop'_  and _oled.state == STATE_PLAYER_ and simply use _oled.modal.UpdatePlayingInfo_ with desired information as artist and song string.
For some advanced screen you can create new "modal" oled.state so that you can define different layout, fonts..
Anyway it would be good to use dimmed brightness or display time limit.

**Comment by Maschine2501** [comment]
Hi,
Thank you for your Answer! I think with the provided information i will be able to make it fit my needs.
I'm realy glad and thankfull!

But may I ask one more thing?
In order to fit my oled display in the case, i needed to mount it upside down... So... Is there a way to rotate it 180°? I've already tried a few things, but not succesfull...

Thank you!

**Comment by diehardsk** [comment]
Rotation should not be a problem. [luma-oled documentation](https://luma-oled.readthedocs.io/en/latest/api-documentation.html)
just change display init to: _oled = ssd1322(interface, rotate=2)_

**Comment by Maschine2501** [comment]
Hi, 
first of all, thanks for replying, rotation works perfectly!
Right now i'm messing with the oledui.py
There's no "oled.playState == 'stop'" to find...
"oled.state == STATE_PLAYER" is present 4 times.
May you give me a tip in which line the "blank screen" part is?

I want to replace it with Time, Date and IP-Adress.

I think this is needed to get the needed informations:

import requests
import os
import time
import sys
import socket


def getWanIP():
    #can be any routable address,
    fakeDest = ("223.5.5.5", 53)
    wanIP = ""
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(fakeDest)
        wanIP = s.getsockname()[0]
        s.close()
    except Exception, e:
        pass
    return wanIP

def GetLANIP():
      cmd = "ip addr show eth0 | grep inet  | grep -v inet6 | awk '{print $2}' | cut -d '/' -f 1"
       p = Popen(cmd, shell=True, stdout=PIPE)
       output = p.communicate()[0]
       return output[:-1]
   
def GetInput():
	cmd = "amixer sget -c 0 'I2S/SPDIF Select' | grep Item0: | awk '{print $2}' "
	p = Popen(cmd, shell=True, stdout=PIPE)
	output = p.communicate()[0]
	return output[:-1]

**Comment by diehardsk** [comment]
I mean, you shoud write some code, where you check this condition oled.playState == 'stop' ...
PLAYER screen + STOP state, this is the blank screen case.

**Comment by Maschine2501** [comment]
Thank you for your reply.
I've tested some stuff, failed many times.
But, i got it running:
https://github.com/Maschine2501/Volumio-OledUI/blob/master/oledui.py

You can close this issue!
Thank's for your support!
