### ISSUE TITLE
ERROR: Package 'luma.core' requires a different Python: 2.7.9 not in '>=3.5, <4'`

### ISSUE THREAD

**Issue by Maschine2501** [diehardsk/Volumio-OledUI#2]
Hi there!
It seems that the end of Python2 support affects Volumio-OledUI.
If want to install it (Volumio 2.729) I got the following Error:
`volumio@volumio:~$ sudo pip install --upgrade socketIO-client-2 luma.oled
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please                                                                                                                                                              upgrade your Python as Python 2.7 is no longer maintained. A future version of                                                                                                                                                              pip will drop support for Python 2.7. More details about Python 2 support in pip                                                                                                                                                             , can be found at https://pip.pypa.io/en/latest/development/release-process/#pyt                                                                                                                                                             hon-2-support
Collecting socketIO-client-2
  Downloading socketIO-client-2-0.7.5.tar.gz (600 kB)
     |################################| 600 kB 3.3 MB/s
Collecting luma.oled
  Downloading luma.oled-3.4.0-py2.py3-none-any.whl (18 kB)
Requirement already satisfied, skipping upgrade: requests in /usr/lib/python2.7/                                                                                                                                                             dist-packages (from socketIO-client-2) (2.4.3)
Requirement already satisfied, skipping upgrade: six in /usr/lib/python2.7/dist-                                                                                                                                                             packages (from socketIO-client-2) (1.8.0)
Collecting websocket-client
  Downloading websocket_client-0.57.0-py2.py3-none-any.whl (200 kB)
     |################################| 200 kB 9.9 MB/s
Collecting luma.core>=1.12.0
  Downloading luma.core-1.14.0-py2.py3-none-any.whl (51 kB)
     |################################| 51 kB 216 kB/s
ERROR: Package 'luma.core' requires a different Python: 2.7.9 not in '>=3.5, <4'`

I tried some things:
- Install Python 3.5.2
- tried it with pip3

If I install it with pip3, then the oledui.py stops, stating "socketIO.client" not found.

After that i installed SocketIO with pip and pip3.. the problem persists.

Actually I have no Idea how to fix that. Maybe you have an Idea?

Best wishes,

Christoph

**Comment by Maschine2501** [comment]
Hi there,
I think it is necessary that we migrate to Python >= 3.5 
I've tried lots of things but did not make any progress...
I will investigate it with some friends, but it would be great if you could have a look at it to.
Regards,
Christoph

**Comment by Maschine2501** [comment]
I think I#ve found a workaround.
With the following changes in the installation it worked for me:


sudo apt-get update
 
sudo apt-get install -y python-dev python-pip libfreetype6-dev libjpeg-dev build-essential python-rpi.gpio
 
sudo pip install setuptools==42.0.0

sudo pip install --upgrade pip wheel

sudo pip install --upgrade socketIO-client-2 

sudo pip install luma.oled==3.0.1

**Comment by diehardsk** [comment]
Hello Christoph,
thanks for sharing. We are mixing some old and new stuff to work together. Maybe we can move to different socketIO-client library. This one claims to support python 3.x:
https://pypi.org/project/socketIO-client/
pip3 install socketIO-client
I checked that it works w/o any change to OledUI script, until now just in my 2.7 python enviroment.
BTW, I like oxanium fonts you're using and I'd like to give appreciation to your coding as well. Keep it up!

**Comment by Maschine2501** [comment]
Hi,
I think this would be the new installtion routine?

sudo apt-get update
 
sudo apt-get install -y python3-dev python3-pip libfreetype6-dev libjpeg-dev build-essential python3-rpi.gpio
 
sudo pip3 install --upgrade setuptools pip wheel
 
sudo pip3 install --upgrade socketIO-client luma.oled

sudo apt-get install python3-pycurl   


I'm testing it in a minute.... ->
https://github.com/Maschine2501/Volumio-OledUI/wiki/Python-3.8.2

**Comment by Maschine2501** [comment]
Hi!
I figured some things out...
I think everything is running fine, except the SocketIO.
You can find what i installed under:
https://github.com/Maschine2501/Volumio-OledUI/wiki/Installation-Steps-(Nightly---Python3)

If i List all Pip 3 Modules:
volumio@volumio:~$ pip3 list
Package          Version
---------------- ----------
aenum            2.2.3
certifi          2020.4.5.1
chardet          3.0.4
idna             2.9
luma.core        1.14.0
luma.oled        3.4.0
Pillow           7.1.1
pip              20.0.2
pyftdi           0.50.0
pyserial         3.4
pyusb            1.0.2
requests         2.23.0
RPi.GPIO         0.7.0
setuptools       46.1.3
six              1.14.0
smbus2           0.3.0
socketIO-client  0.7.2
spidev           3.4
urllib3          1.25.8
websocket-client 0.57.0
wheel            0.34.2

You will notice that socketIO ist listet with a "-" and not with a "_" (as described in the [documentation](https://pypi.org/project/socketIO-client/) )
If i do "from socketIO-client import SocketIO" i get an Syntax error.
If i do "from socketIO_client import SocketIO" it states that no module named socketIO_client found...
Perhaps you can repeat my installation steps and have a look at it?

For me it seems to be the "only Problem" right now.

**Comment by diehardsk** [comment]
I'm trying to use python3.7.7 / 3.8.2, but I didn't get far. pip3 states there's no ssl module. Can you check for me: volumio@volumio:~$ openssl version
mine is OpenSSL 1.0.1t  3 May 2016

**Comment by Maschine2501** [comment]
> 
> 
> I'm trying to use python3.7.7 / 3.8.2, but I didn't get far. pip3 states there's no ssl module. Can you check for me: volumio@volumio:~$ openssl version
> mine is OpenSSL 1.0.1t 3 May 2016

Hi,
i didn't mentioned it, sorry.
I've had same ssl issue wit python 3.8.2...
Somewhere was stated that 3.8, 3.7 are not for the use on a raspberry..
I was not able to resolve the ssl problem.

Therfore I've changed to 3.5.2.
Which actually is working "fine"... excluding the "socketIO" problem...

**Comment by Maschine2501** [comment]
volumio@volumio:~$ openssl version
OpenSSL 1.0.1t  3 May 2016
volumio@volumio:~$ python --version
Python 2.7.9
volumio@volumio:~$ python3 --version
Python 3.5.2

**Comment by Maschine2501** [comment]
PS: If you want, we can make a discord channel, maybe this would help us to solve this problem faster?

**Comment by Maschine2501** [comment]
Good Evening!
I've good news!
I just got my version of Volumio-OledUI running in Python3(.5.2).
.
.
.
But!
The Script only works, if i start it with:
"sudo python3 Volumio-OledUI/oledui-nightlyPY3.py"
Otherwise (.service) it keeps saying "no module socketIO_client found"

I tried some things with the .service file, but did not solve this problem...

So maybe give it a shot ;)
https://github.com/Maschine2501/Volumio-OledUI/wiki/Installation-Steps-(Nightly---Python3)

**Comment by diehardsk** [comment]
Hello, that sounds good. Maybe there's only problem with path where socketIO_client is installed. Check "pip3 show SocketIO-client". And you can probably tell pip where to install.
I didn't succeed with python3.5.2 neither, maybe I messed up something with openssl before.

**Comment by Maschine2501** [comment]
I advise to get a clean start ;)

What did you mean by "tell pip where to install"?

volumio@volumio:~$ pip3 show SocketIO-client
Name: socketIO-client
Version: 0.7.2
Summary: A socket.io client library
Home-page: https://github.com/invisibleroads/socketIO-client
Author: xxxxxxxxxxxxxxxxxxx
Author-email: rhh@xxxxxxxxxx
License: MIT
Location: /usr/local/lib/python3.5/site-packages
Requires: websocket-client, six, requests
Required-by:

**Comment by diehardsk** [comment]
Yes, it realy needs new clean sd image. Someday :-)
Your path looks normal. If you take a look at [instructions](https://pypi.org/project/socketIO-client/), they are using isolated environment, so you may try to install this virtualenv. I have never used that before.

**Comment by Maschine2501** [comment]
I read the instructions. But with sudo it worked anyway, so i guess it's not needed... But i'll try it

**Comment by Maschine2501** [comment]
Edit:
After i uninstalled socket IO and reinstalled it with:
"sudo pip install --target=/usr/local/lib/python3.5/site-packages socketIO-client"
it is functional by starting it manually with"python3 oledui-nightlyPY3.py" 

But now somehow the .service is not working anymore...

**Comment by diehardsk** [comment]
in .service file in your respository I see
"ExecStart=/usr/bin/python -u /home/volumio/Volumio-OledUI/oledui-nightlyPY3.py"
--> forgot to change to python3 ?

**Comment by Maschine2501** [comment]
> 
> 
> in .service file in your respository I see
> "ExecStart=/usr/bin/python -u /home/volumio/Volumio-OledUI/oledui-nightlyPY3.py"
> --> forgot to change to python3 ?

Yeah, i changed it on the Pi to python3 allready, with no success.
I just removed OledUI completely, changed the srvice file to Python3 (in github) and made a clean install.
After reboot this is the journal:
volumio@volumio:~$ sudo journalctl -fu oledui-nightlyPY3.service
-- Logs begin at Tue 2020-04-14 06:42:51 CEST. --
Apr 14 06:42:55 volumio systemd[1]: Starting Volumio oled UI nightly...
Apr 14 06:42:55 volumio systemd[1]: Started Volumio oled UI nightly.
Apr 14 06:42:57 volumio oledui-nightlyPY3[631]: Traceback (most recent call last):
Apr 14 06:42:57 volumio oledui-nightlyPY3[631]: File "/home/volumio/Volumio-OledUI/oledui-nightlyPY3.py", line 18, in <module>
Apr 14 06:42:57 volumio oledui-nightlyPY3[631]: from socketIO_client import SocketIO
Apr 14 06:42:57 volumio oledui-nightlyPY3[631]: ImportError: No module named 'socketIO_client'
Apr 14 06:42:57 volumio systemd[1]: oledui-nightlyPY3.service: main process exited, code=exited, status=1/FAILURE
Apr 14 06:42:57 volumio systemd[1]: Unit oledui-nightlyPY3.service entered failed state.

But if i start it normaly everything is ok, display and code working like charm:
volumio@volumio:~$ python3 Volumio-OledUI/oledui-nightlyPY3.py
b'Absolut Radio'
Queue length is 1
b''
b''
b''
b'Aerosmith - Amazing | Absolut Radio '
b'Aerosmith - Amazing | Absolut Radio '
b'Ray Charles - You Were There | Absolut Radio '
b'Ray Charles - You Were There | Absolut Radio '

**Comment by diehardsk** [comment]
You are so close :-) But where's the problem..
check /usr/bin/python3 -V
probably correct path is now /usr/local/bin/python3
You can also check other modules like luma being accessible. execute /usr/local/bin/python3
and "import luma.core", "import socketIO_client"

**Comment by Maschine2501** [comment]
> 
> 
> You are so close :-) But where's the problem..
> check /usr/bin/python3 -V
> probably correct path is now /usr/local/bin/python3
> You can also check other modules like luma being accessible. execute /usr/local/bin/python3
> and "import luma.core", "import socketIO_client"

Holy Fu**** Sh**...
It was the path:  /usr/local/bin/python3
Thank you for your assistance!!!

I've changed it in my repository, maybe you can test if my installation routine is working for you?
Or if there are steps which are not needed?!

**Comment by diehardsk** [comment]
Happy to hear that!
I'm not moving to python3 these days. It would be best if volumio itself is built on later raspbian.
If I were you, I would recheck socketIO-client realy needs to install to user directory. Just to sit along with other modules if possible.
Thank you too! Nice cooperation.
