### ISSUE TITLE
License / Contributor

### ISSUE THREAD

**Issue by Maschine2501** [diehardsk/Volumio-OledUI#3]
Hi,
sorry for opening this request as an issue, but i haven't found another way to contact you.
As you allready know, your code "Volumio-OledUI" was the base of my code.
Your work was a huge inspiration and without your previous efforts it would'nt been possible to reach the functions i now have in my code.

My request:
In my repository i have icluded the [license informations](https://github.com/Maschine2501/NR1-UI/blob/master/LICENSE.md) of your code.

I kindly ask you, if I'm allowed to remove your license Informations from [my Code](https://github.com/Maschine2501/NR1-UI).

I promise that the first sentence of my Readme.md **allways** will be: "Inspired by [diehardsk/Volumio-OledUI](https://github.com/diehardsk/Volumio-OledUI)"

So i don't want to "steal" your code and/or want to dishonor your efforts, but in my opinion, my code has evolved so much, that there is not much of the source left.

Thank you and best wishes,

Christoph

**Comment by diehardsk** [comment]
Hello Christoph,
You made realy a great job in jour project! It's amazing to see so much progress.
My code is free for any use case and I'm happy it was an original inspiration for you.

Thank you and good luck.
Diehard
